const codes = {
  NOT_FOUND_ERROR_CODE: 404,
  INTERNAL_SERVER_ERROR_CODE: 500,
  BAD_REQUEST_ERROR_CODE: 400,
  SUCCESS_OK_CODE: 200,
  UNAUTHORIZED_CODE: 401,
  SUCCESS_CREATED_CODE: 201,
  FORBIDDEN_CODE: 403,
  CONFLICT_CODE: 409,
};

module.exports = codes;
